### PR TITLE
Add: multiples disposable email domains

### PR DESCRIPTION
**Pull request by Zeuh**
Sources :

https://tempmail.net/               : yevme.com
https://www.tempmailaddress.com/    : ldaho.biz
https://generator.email/            : dlesha.ru
                                      hydraulics360.ru
                                      3d-magical-magnet.ru
                                      90bit.ru
                                      awex.icu
                                      vkusup.ru
                                      sgbteamreborn.imouto.pro
                                      choocho-telegram.ru
                                      funny-mom.ru
                                      ekholotdeeper.ru
                                      newfilm24.ru
                                      titaspaharpur1.gq
                                      mineblue.ru
                                      shar-kov.ru
                                      piratesdelivery.ru
                                      audio.now.im
                                      goplaygame.ru
                                      sskstroy.ru
                                      edu.aiot.ze.cx
                                      misha-rosestoy.ru
                                      furycraft.ru
                                      light-marketing.ru
                                      reloadpoint.ru
                                      1054733.mail-temp.com
                                      s-sakamas.ru
                                      dmaster39.ru
                                      fotosta.ru
                                      vapecentral.ru
                                      zdorovpagh.ru
                                      barenshop.ru
https://mail-temp.com/              : gnomi.ru
                                      pchelovodstvo-tut.ru
                                      h2ocoffe.ru
                                      zagorodnyi-domik.ru
                                      domremonta-nv.ru
                                      powerbank-russia.ru
                                      madecassol78.ru
                                      kemampuan.me
                                      partner1bizmoney.ru
                                      kkm35.ru
                                      razinrocks.me
                                      justyland.ru
                                      samogonda.ru
                                      officialrolex.ru
https://10minutemail.com/           : urhen.com
https://mytemp.email                : i.xcode.ro
                                      mailfs.com
                                      xww.ro
                                      barryogorman.com
                                      vssms.com
                                      isdaq.com
                                      mailed.ro
                                      laoho.com
                                      pmlep.de
                                      tvchd.com
                                      mor19.uu.gl
                                      alaki.ga
                                      kusrc.com
                                      cetpass.com
                                      ussv.club
                                      dfg6.kozow.com
                                      maildx.com
                                      fls4.gleeze.com
http://tempmail.pp.ua/              : p33.org
http://10minut.com.pl/              : 10m.email
http://10minutesmail.com/           : 10minutesmail.com
https://www.1secmail.com/           : 1secmail.com
                                      1secmail.org
                                      1secmail.net
https://disposeamail.com/           : disposeamail.com
https://www.squizzy.net/            : squizzy.net
https://www.tempemails.net/         : lifeguru.online
                                      weammo.xyz
                                      moboinfo.xyz
                                      tecninja.xyz
                                      onlinenet.info
                                      webcool.club
http://bluemixe2e.mailinator.com/   : mailinator.com
https://www.tempemails.net/         : onlinenet.info
                                      webcool.club
                                      weammo.xyz
                                      moboinfo.xyz
                                      tecninja.xyz
                                      lifeguru.online
https://www.teleosaurs.xyz/         : teleosaurs.xyz
https://www.tempmailbox.net/        : exbts.com
http://trashmail.ws/                : trashmail.ws
http://dispomail.xyz/               : dispomail.xyz
http://trashinbox.net/              : trashinbox.net
http://spambox.xyz/                 : spambox.xyz
                                      tempmail.win
http://tempmail.top/                : tempmail.top
                                      spambox.win
                                      dispomail.win
https://xitroo.com/                 : xitroo.com

Signed-off-by: Yann 'Ze' Richard <ze@nbox.org>

### CODE REVIEW

**Comment by moisseev** [comment]
As I can see, you've reordered the map. What ordering are your proposing instead of unix sort ordering?

Some tempmail services like `mail-temp.com` and `generator.email` don't show their full domain lists. Web forms generate domain lists dynamically. If you reload the page you get another portion of domains. I have no idea how big is the full list.
Another concern, I don't know how long these domain live. If it is for several days, I am not sure if it worth to add them to the map.

**Comment by Zeuh** [comment]
Yes, the list have been reordered by unix sort to add domains to the list I have used : sort -u -o file file (on Debian 9).

For obsolescence concerns, perhaps we can add only domains created for more than 2 years ?

**Comment by moisseev** [comment]
GNU sort is a weird thing. Would you please use the traditional sort order like `LC_ALL=C sort -u -o file file` instead?

```
moiseev@debian:~$ cat list.txt
a-b
ac-b
ac-d
a-d
moiseev@debian:~$ sort list.txt
a-b
ac-b
ac-d
a-d
```

The sort order looks confusing to me.

```
moiseev@debian:~$ LC_ALL=C sort list.txt
a-b
a-d
ac-b
ac-d
```
Isn't it better?

**Comment by Zeuh** [comment]
Visually yes it's more comfortable. After I am agnostic, the main thing is to use the same sorting :)

For list, do you want a pull request with only domains older than 2 years ?

**Comment by moisseev** [comment]
No, please keep them all. I think most of these domains are registered for 1 year.

**Pull request closed without merging**
